version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --bind-address=0.0.0.0   # Allow connections from all IPs
    networks:
      - app-network

  app:
    build: .
    container_name: todo_app
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/tododb
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge