server:
  applicationContextPath: /api/v1
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081


database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: Mudal@p3
  url: jdbc:mysql://localhost:3306/dropwizard
