server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /api/v1

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: password
  url: jdbc:mysql://mysql:3306/tododb
